management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always


resilience4j:
  circuitbreaker:
    instances:
      catalog_item_service:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      user_rating_service:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 6
        ringBufferSizeInHalfOpenState: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 60

